---
- include_tasks: configure/create-broker.yml
  when: config_mode == 'generated'

- include_tasks: configure/tls.yml
  when: config_mode == 'generated' and amq_broker_tls

- include_tasks: configure/shared_storage.yml
  when: config_mode == 'generated' and amq_broker_shared_storage

- include_tasks: configure/clustering.yml
  when: config_mode == 'generated' and amq_broker_clustered

- include_tasks: configure/ports.yml
  when: config_mode == 'generated'

- include_tasks: configure/users-roles.yml
  when: config_mode == 'generated'

- include_tasks: configure/static.yml
  when: config_mode == 'static'

- include_tasks: configure/logging.yml

- include_tasks: configure/plugins.yml

- include_tasks: configure/service.yml
