---

- name: install - copy Red Hat AMQ
  copy:
    src: "{{ jboss_amq_artifact_name }}"
    dest: "{{ jboss_amq_artifact_tmp_dest }}"
    remote_src: yes

- name: install - set Location for Copy of Red Hat AMQ
  set_fact:
    amq_distribution: "{{ jboss_amq_artifact_tmp_dest }}"
    amq_remote_src: yes
