---

- block:
  - name: Async Download Red Hat AMQ from Red Hat Customer Portal
    redhat_csp_download:
      url: "{{ amq_artifact_source }}"
      dest: "{{ amq_artifact_tmp_dest }}"
      username: "{{ rhn_username }}"
      password: "{{ rhn_password }}"
    async: 7200
    poll: 0
    register: amq_download
  - name: 'Check On AMQ Download Completion'
    async_status: jid={{ amq_download.ansible_job_id }}
    register: job_result3
    until: job_result3.finished
    retries: 600
    delay: 10
  - name: Set Location for Copy of AMQ
    set_fact:
      amq_distribution: "{{ amq_artifact_tmp_dest }}"
      amq_remote_src: yes
  when: transfer_method == 'csp-to-host' and amq_exists.stat.exists == false
